name: eds220-env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.7.1
  - python=3.11.4
  - pip=23.3.1
  - ipykernel
  - numpy=1.24.3
  - rioxarray=0.14.1
  - libgdal-netcdf
  - netcdf4
